frameworkVersion: '>=3.0.0'
service: ${self:custom.platformName}
provider:
  name: google
  runtime: nodejs18
  stage: ${opt:stage, 'devel'}
  project: ${self:custom.platformName}
  environment:
    PLATFORM_NAME: ${self:custom.platformName}
    ENV_STAGE: ${self:provider.stage}
custom:
  isProd:
    prod: true
  prefix: ${opt:stage, self:provider.stage}-${self:custom.platformName}
  stage: ${opt:stage, self:provider.stage}
  platformName: gcp-serverless-function
plugins:
  - serverless-google-cloudfunctions

package:
  include:
    - ./src/handler.ts
  exclude:
    - node_modules/**
    - .gitignore
    - .git/**

functions:
  hello:
    name: ${self:custom.prefix}-hello
    handler: http
    timeout: 30
    events:
      - http:
          path: hello
          method: get
