frameworkVersion: '>=3.0.0'
service: ${self:custom.platformName}
provider:
  name: google
  credentials: ".gcloud/keyfile.json"
  runtime: nodejs18
  stage: ${opt:stage, 'devel'}
  project: "chromatic-baton-422517-g2"
  environment:
    PLATFORM_NAME: ${self:custom.platformName}
    ENV_STAGE: ${self:provider.stage}
custom:
  isProd:
    prod: true
  prefix: ${opt:stage, self:provider.stage}-${self:custom.platformName}
  stage: ${opt:stage, self:provider.stage}
  platformName: gcp-serverless-function
plugins:
  - serverless-google-cloudfunctions

functions:
  hello:
    name: ${self:custom.prefix}-hello
    handler: hello
    events:
      - http: true
