resources:
  - type: storage.v1.bucket
    name: sls-gcp-serverless-function-devel-1715626554949
  - type: gcp-types/cloudfunctions-v1:projects.locations.functions
    name: devel-gcp-serverless-function-hello
    properties:
      parent: projects/chromatic-baton-422517-g2/locations/us-central1
      availableMemoryMb: 256
      runtime: nodejs18
      timeout: 60s
      entryPoint: hello
      function: devel-gcp-serverless-function-hello
      sourceArchiveUrl: >-
        gs://sls-gcp-serverless-function-devel-1715626554949/serverless/gcp-serverless-function/devel/1715630036224-2024-05-13T19:53:56.224Z/gcp-serverless-function.zip
      environmentVariables:
        PLATFORM_NAME: gcp-serverless-function
        ENV_STAGE: devel
      labels: {}
      httpsTrigger:
        url: 'true'
